// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString`
//     Provider:               `System.Data.SqlServerCe.4.0`
//     Connection String:      `Data Source=C:\Users\jmdehlin\Projects\ToDoOnionArchitecture\ToDoApp.Website\App_Data\\ToDoDatabase.sdf`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoApp.Application.Models.Database
{
    /// <summary>
    /// A class which represents the ToDoItems table.
    /// </summary>
	[Table("ToDoItems")]
	public partial class ToDoItem
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Body { get; set; }
		public virtual int Status { get; set; }
		public virtual int UserId { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual DateTime? UpdatedAt { get; set; }
	}

    /// <summary>
    /// A class which represents the ToDoLists table.
    /// </summary>
	[Table("ToDoLists")]
	public partial class ToDoList
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Title { get; set; }
		public virtual int UserId { get; set; }
		public virtual DateTime CreatedAt { get; set; }
	}

    /// <summary>
    /// A class which represents the Users table.
    /// </summary>
	[Table("Users")]
	public partial class User
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
	}

}
