// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `MultipleActiveResultSets=True;Data Source=.\sqlexpress;Initial Catalog=ToDoApp;Integrated Security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoApp.Domain.DataTransfer
{
    /// <summary>
    /// A class which represents the ToDoItems table.
    /// </summary>
	[Table("ToDoItems")]
	public class ToDoItem : Models.BaseModel
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int UserId { get; set; }
		public virtual string Body { get; set; }
		public virtual Models.ToDoItem.ToDoItemStatus Status { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual DateTime CreatedAt { get; set; }
	}

    /// <summary>
    /// A class which represents the ToDoLists table.
    /// </summary>
	[Table("ToDoLists")]
	public class ToDoList : Models.BaseModel
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int UserId { get; set; }
		public virtual string Title { get; set; }
		public virtual DateTime CreatedAt { get; set; }
	}

    /// <summary>
    /// A class which represents the Users table.
    /// </summary>
	[Table("Users")]
	public class User : Models.BaseModel
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime CreatedAt { get; set; }
	}

}
